apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: "K8s"
  controllerUrl: "http://10.60.40.122:8090"
  account: "customer1"
  # docker image info
  image: "appdynamics/cluster-agent"
  serviceAccountName: appdynamics-cluster-agent
  ### Uncomment the following line if you need pull secret
  #imagePullSecret: "<your-docker-pull-secret-name>"
  nsToMonitorRegex: default
  nsToInstrumentRegex: default
  stdoutLogging: "true"
  instrumentationMethod: Env
  appNameStrategy: label
  #logLevel: DEBUG
  instrumentationRules:
    - language: dotnetcore
      appNameLabel: app
      namespaceRegex: default
      appName: Openshift
      imageInfo:
        image: "docker.io/appdynamics/dotnet-core-agent:21.9.1"
        agentMountPath: /opt/appdynamics
