apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: "K8s"
  controllerUrl: "https://greennetworksllc-nfr.saas.appdynamics.com:443"
  account: "greennetworksllc-nfr"
  # docker image info
  image: "appdynamics/cluster-agent"
  serviceAccountName: appdynamics-cluster-agent
  ### Uncomment the following line if you need pull secret
  #imagePullSecret: "<your-docker-pull-secret-name>"
  nsToMonitorRegex: default
  nsToInstrumentRegex: default
  stdoutLogging: "true"
  instrumentationMethod: Env
  appNameStrategy: label
  #logLevel: DEBUG
  instrumentationRules:
    - language: nodejs 
      appNameLabel: app
      imageInfo:
        image: "docker.io/appdynamics/nodejs-agent:21.6.0-16-stretch-slim"
        agentMountPath: /opt/appdynamics
