apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: adams.appdynamics.com
spec:
  group: appdynamics.com
  names:
    kind: Adam
    listKind: AdamList
    plural: adams
    singular: adam
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true