apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustercollectors.appdynamics.com
spec:
  group: appdynamics.com
  names:
    kind: Clustercollector
    listKind: ClustercollectorList
    plural: clustercollectors
    singular: clustercollector
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
